services:
    job-tracking-api:
        build: .
        container_name: job-tracking-api
        ports:
            - "8002:8000"
            - "8003:8001"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:8000;http://+:8001
            - DOTNET_USE_POLLING_FILE_WATCHER="1"
            - PORT=8000
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=postgres
            - JWT_SECRET=Sk1bidi0Hi0R1zz
            - ASPNETCORE_Kestrel__Certificates__Default__Password=test
            - ASPNETCORE_Kestrel__Certificates__Default__Path=../https/aspnetapp.pfx 
        volumes:
            - .:/app
            - /app/db/
        command: ["dotnet", "watch","run", "-v", "--non-interactive", "--project" , "JobTracking.API/JobTracking.API.csproj"]
        depends_on:
            - db
    db:
        image: postgres:16
        volumes:
            - ./db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

volumes:
    pgadmin-data:
    data:
